---
title: "Spiny Lobster Management"
resource_files:
- spiny.png
runtime: shiny
output:
  flexdashboard::flex_dashboard:
    social: menu
    source_code: embed
---

```{r setup, include=FALSE}
library(flexdashboard)
library(devtools)
library(leaflet)
library(highcharter)
library(markdown)
library(shiny)
library(rgdal)
library(maptools)
library(leaflet.esri)
devtools::install_github("rstudio/rmarkdown")
# devtools::install_github("rstudio/flexdashboard", ref="bugfix/dashboard-init-after-body")

# lobPoly <- readOGR(dsn="LobsterManagementAreas.shp",layer="LobsterManagementAreas")
# proj4string(lobPoly) <- CRS("+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs")
# 
# buffPoly <- readOGR(dsn="clippedBuffer_UTM.shp",layer="clippedBuffer_UTM")
# buffPoly<- spTransform(buffPoly,CRS("+init=epsg:4326"))
# proj4string(buffPoly) <- CRS("+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs")
# 
# both <- readOGR(dsn="bufferClosedAreas_UTM.shp",layer="bufferClosedAreas_UTM")
# both<- spTransform(both,CRS("+init=epsg:4326"))
# proj4string(both) <- CRS("+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs")
# 
# geoTest <- readOGR(dsn="geoTest.shp",layer="geoTest")
# geoTest<- spTransform(geoTest,CRS("+init=epsg:4326"))
# proj4string(geoTest) <- CRS("+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs")
# 
# buff <- readOGR(dsn="geoTestBuffDif.shp",layer="geoTestBuffDif")
# buff<- spTransform(buff,CRS("+init=epsg:4326"))
# proj4string(buff) <- CRS("+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs")
# basemaps <- esriBasemapLayers
# #both <- spRbind(geoTest,buff)
# 
# both <- readOGR(dsn="merge2.shp",layer="merge2")
# proj4string(both) <- CRS("+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs")
load("lobsterPolygons.RData")
```

<!-- Column {data-width=650} -->
<!----------------------------------------------------------------------->

### Lobster Trap Closed Areas 

```{r}
#actionButton('do',"Find ME")
#tableOutput('table')
 #fillCol(height = 600,flex = 1,
  leafletOutput('map',height=460,width=460)#,
  # absolutePanel(id = "controls", class = "panel panel-default", fixed = FALSE,
  #                        draggable = TRUE, top = 100, left = "auto", right = 20, bottom = "auto",
  #                        width = 230, height = "auto",
  #             wellPanel(actionButton('do',"Find ME"))
#)#)

## script includes necessary geolocation code ##
#includeScript('geoloc.js')
#includeScript('geoloc2.js')
## script for splash page ##################
 includeHTML('modalHTML2.html')
 includeScript('modalJS.js')
####################################
#includeCSS('modalCSS.css')
#includeHTML('button.html')


###### render basemap #####

output$map <- renderLeaflet({  
  l <- leaflet() %>% setView(-81, 25, zoom = 9) %>% 
        addEsriBasemapLayer(esriBasemapLayers$Imagery) %>%
        addMiniMap(tiles="Esri.WorldImagery") %>% 
        addPolygons(data=lobPoly, color="yellow",stroke=FALSE,fillOpacity=1.0,layerId=~ET_ID) %>% 
        #addPolygons(data=buff,color='green', stroke = FALSE, fillOpacity=1.0,layerId=~id) %>% 
        addLegend(position='bottomleft',colors='yellow', labels='Spiny Lobster Closed Areas',opacity=1.0) %>% 
        addControlGPS()
        # addControl(
        #   actionButton('do',"Find ME")
        # )
       })

#### subsets closed areas by geolocated lat/long points ####
closed <- reactive({
  lat <- input$map_gps_located$coordinates$lat
  lon <- input$map_gps_located$coordinates$lng
  
  #puts lat and lon for click point into its own data frame
      coords <- as.data.frame(cbind(lon, lat))

      #converts click point coordinate data frame into SP object, sets CRS
      point <- SpatialPoints(coords)
      proj4string(point) <- CRS("+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs")

      #retrieves country in which the click point resides, set CRS for country
      selected <- lobPoly[point,]
      proj4string(selected) <- CRS("+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs")
      
      selected
})

#### subsets buffered area by geolocated lat/long points ###

buffer <- reactive({
  lat <- input$map_gps_located$coordinates$lat
  lon <- input$map_gps_located$coordinates$lng
  
  #puts lat and lon for click point into its own data frame
      coords <- as.data.frame(cbind(lon, lat))

      #converts click point coordinate data frame into SP object, sets CRS
      point <- SpatialPoints(coords)
      proj4string(point) <- CRS("+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs")

      #retrieves country in which the click point resides, set CRS for country
      selected <- buffPoly[point,]
      proj4string(selected) <- CRS("+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs")
      
      selected
})

notclosed <- reactive({
  lat <- input$map_gps_located$coordinates$lat
  lon <- input$map_gps_located$coordinates$lng
  
  #puts lat and lon for click point into its own data frame
      coords <- as.data.frame(cbind(lon, lat))

      #converts click point coordinate data frame into SP object, sets CRS
      point <- SpatialPoints(coords)
      proj4string(point) <- CRS("+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs")

      #retrieves country in which the click point resides, set CRS for country
      selected <- both[point,]
      proj4string(selected) <- CRS("+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs")
      
      selected
})

#### projects geolocated coordinates in a dataframe ###############

LatLong <- reactive({
  lat <- input$map_gps_located$coordinates$lat
  lon <- input$map_gps_located$coordinates$lng
  
  #puts lat and lon for click point into its own data frame
      coords <- as.data.frame(cbind(lon, lat))

      coords
})


 ####### Observer changes closed area polygon color if user's geolocation is inside polygon #######
observe({
  geo <- input$map_gps_located

  if (is.null(geo))
    return ()

  
      proxy <- leafletProxy("map",data=closed())
      if(nrow(closed())<1){
        proxy %>% removeShape(layerId = "Selected") 
        
      } else {
        proxy %>% addPolygons(data = closed(),
                              fillColor = "#e7298a",
                              fillOpacity = 1,
                              color = "#e7298a",
                              stroke = FALSE,
                              layerId = "Selected") 
          
      }
      

 })

####### Observer changes buffer area polygon color if user's geolocation is inside polygon #######

observe({
  geo <- input$map_gps_located

  if (is.null(geo))
    return ()

  
      proxy <- leafletProxy("map",data=buffer())
      if(nrow(buffer())<1){
        proxy %>% removeShape(layerId = "Selected2") 
        
      } else {
        proxy %>% addPolygons(data = buffer(),
                              fillColor = "#a87000",
                              fillOpacity = 1,
                              color = "#a87000",
                              stroke = FALSE,
                              layerId = "Selected2") 
          
      }
      

 })

####### Observer generates warning popup if user's geolocation is within a closed area polygon #######

observe({
  geo <- input$map_gps_located

  if (is.null(geo))
    return ()
  
    content <- paste(sep = "<br/>",
  "<b>Warning:</b>",
  "You are in a closed area.",
  "Trap fishing for spiny lobster is not allowed here.",
  "<a href='http://sero.nmfs.noaa.gov/maps_gis_data/fisheries/gom/documents/lobster_trap.txt' target='_blank'>Federal regulations</a>"
                              
)

      proxy <- leafletProxy("map",data=closed())
      if(nrow(closed())<1){
        proxy %>% removePopup(layerId = "popup1")

      } else {
        proxy %>% addPopups(lng=LatLong()$lon,lat=LatLong()$lat, content,
                              layerId='popup1')

      }


 })

####### Observer generates warning popup if user's geolocation is within a buffer area polygon #######

observe({
  geo <- input$map_gps_located

  if (is.null(geo))
    return ()
  
    content <- paste(sep = "<br/>",
  "<b>Warning:</b>",
  "You are within 1km of a closed area"
  
)

      proxy <- leafletProxy("map",data=buffer())
        if(nrow(buffer())<1){
        proxy %>% removePopup(layerId = "popup2")

      } else {
        proxy %>% addPopups(lng=LatLong()$lon,lat=LatLong()$lat, content,
                              layerId='popup2')

      }


 })

####### Observer generates popup if user's geolocation is NOT within a closed area/buffer polygon #######

observe({
  geo <- input$map_gps_located

  if (is.null(geo))
    return ()
  
    content <- paste(sep = "<br/>",
  "<b>Congrats!</b>",
  "You aren't in a closed area."
  
)

      proxy <- leafletProxy("map",data=notclosed())
      if(nrow(notclosed())>=1){
        proxy %>% removePopup(layerId = "popup3")

      } else {
        proxy %>% addPopups(lng=LatLong()$lon,lat=LatLong()$lat, content,
                              layerId='popup3')

      }


 })


#### updates map bounds based on user's geolocation and add a marker at user's location ###
  # observeEvent(input$do,{
  #   if(!is.null(input$map_gps_located)){
  #     map <- leafletProxy("map")
  #     dist <- 0.5
  #     lat <- input$lat
  #     lng <- input$long
  #     map %>% fitBounds(lng - dist, lat - dist, lng + dist, lat + dist) %>%
  #     addMarkers(lng,lat) #%>%
  # 
  #   }
  # })
  
  #output$table <- renderTable(notclosed())


```

<!-- ### Lobster Trap Closed Areas {.mobile} -->

<!-- ```{r} -->
<!-- #actionButton('do',"Find ME") -->
<!-- #tableOutput('table') -->
<!--  #fillCol(height = 600,flex = 1, -->
<!--   leafletOutput('map.m',height=460,width=460)#, -->
<!--   # absolutePanel(id = "controls", class = "panel panel-default", fixed = FALSE, -->
<!--   #                        draggable = TRUE, top = 100, left = "auto", right = 20, bottom = "auto", -->
<!--   #                        width = 230, height = "auto", -->
<!--   #             wellPanel(actionButton('do',"Find ME")) -->
<!-- #)#) -->

<!-- ## script includes necessary geolocation code ## -->
<!-- #includeScript('geoloc.js') -->
<!-- #includeScript('geoloc2.js') -->
<!-- includeHTML('modalHTML2.html') -->
<!-- includeScript('modalJS.js') -->
<!-- #includeCSS('modalCSS.css') -->
<!-- #includeHTML('button.html') -->


<!-- ###### render basemap ##### -->

<!-- output$map.m <- renderLeaflet({   -->
<!--   l <- leaflet() %>% setView(-81, 25, zoom = 9) %>%  -->
<!--         addEsriBasemapLayer(esriBasemapLayers$Imagery) %>% -->
<!--         #addMiniMap(tiles="Esri.WorldImagery") %>%  -->
<!--         addPolygons(data=lobPoly, color="yellow",stroke=FALSE,fillOpacity=1.0,layerId=~ET_ID) %>%  -->
<!--         #addPolygons(data=buff,color='green', stroke = FALSE, fillOpacity=1.0,layerId=~id) %>%  -->
<!--         addLegend(position='bottomleft',colors='yellow', labels='Spiny Lobster Closed Areas',opacity=1.0) %>%  -->
<!--         addControlGPS() -->
<!--         # addControl( -->
<!--         #   actionButton('do',"Find ME") -->
<!--         # ) -->
<!--        }) -->

<!-- #### subsets closed areas by geolocated lat/long points #### -->
<!-- closed <- reactive({ -->
<!--   lat <- input$map.m_gps_located$coordinates$lat -->
<!--   lon <- input$map.m_gps_located$coordinates$lng -->

<!--   #puts lat and lon for click point into its own data frame -->
<!--       coords <- as.data.frame(cbind(lon, lat)) -->

<!--       #converts click point coordinate data frame into SP object, sets CRS -->
<!--       point <- SpatialPoints(coords) -->
<!--       proj4string(point) <- CRS("+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs") -->

<!--       #retrieves country in which the click point resides, set CRS for country -->
<!--       selected <- lobPoly[point,] -->
<!--       proj4string(selected) <- CRS("+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs") -->

<!--       selected -->
<!-- }) -->

<!-- #### subsets buffered area by geolocated lat/long points ### -->

<!-- buffer <- reactive({ -->
<!--   lat <- input$map.m_gps_located$coordinates$lat -->
<!--   lon <- input$map.m_gps_located$coordinates$lng -->

<!--   #puts lat and lon for click point into its own data frame -->
<!--       coords <- as.data.frame(cbind(lon, lat)) -->

<!--       #converts click point coordinate data frame into SP object, sets CRS -->
<!--       point <- SpatialPoints(coords) -->
<!--       proj4string(point) <- CRS("+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs") -->

<!--       #retrieves country in which the click point resides, set CRS for country -->
<!--       selected <- buffPoly[point,] -->
<!--       proj4string(selected) <- CRS("+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs") -->

<!--       selected -->
<!-- }) -->

<!-- notclosed <- reactive({ -->
<!--   lat <- input$map.m_gps_located$coordinates$lat -->
<!--   lon <- input$map.m_gps_located$coordinates$lng -->

<!--   #puts lat and lon for click point into its own data frame -->
<!--       coords <- as.data.frame(cbind(lon, lat)) -->

<!--       #converts click point coordinate data frame into SP object, sets CRS -->
<!--       point <- SpatialPoints(coords) -->
<!--       proj4string(point) <- CRS("+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs") -->

<!--       #retrieves country in which the click point resides, set CRS for country -->
<!--       selected <- both[point,] -->
<!--       proj4string(selected) <- CRS("+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs") -->

<!--       selected -->
<!-- }) -->

<!-- #### projects geolocated coordinates in a dataframe ############### -->

<!-- LatLong <- reactive({ -->
<!--   lat <- input$map.m_gps_located$coordinates$lat -->
<!--   lon <- input$map.m_gps_located$coordinates$lng -->

<!--   #puts lat and lon for click point into its own data frame -->
<!--       coords <- as.data.frame(cbind(lon, lat)) -->

<!--       coords -->
<!-- }) -->


<!--  ####### Observer changes closed area polygon color if user's geolocation is inside polygon ####### -->
<!-- observe({ -->
<!--   geo <- input$map.m_gps_located -->

<!--   if (is.null(geo)) -->
<!--     return () -->


<!--       proxy <- leafletProxy("map.m",data=closed()) -->
<!--       if(nrow(closed())<1){ -->
<!--         proxy %>% removeShape(layerId = "Selected")  -->

<!--       } else { -->
<!--         proxy %>% addPolygons(data = closed(), -->
<!--                               fillColor = "#e7298a", -->
<!--                               fillOpacity = 1, -->
<!--                               color = "#e7298a", -->
<!--                               stroke = FALSE, -->
<!--                               layerId = "Selected")  -->

<!--       } -->


<!--  }) -->

<!-- ####### Observer changes buffer area polygon color if user's geolocation is inside polygon ####### -->

<!-- observe({ -->
<!--   geo <- input$map.m_gps_located -->

<!--   if (is.null(geo)) -->
<!--     return () -->


<!--       proxy <- leafletProxy("map.m",data=buffer()) -->
<!--       if(nrow(buffer())<1){ -->
<!--         proxy %>% removeShape(layerId = "Selected2")  -->

<!--       } else { -->
<!--         proxy %>% addPolygons(data = buffer(), -->
<!--                               fillColor = "#a87000", -->
<!--                               fillOpacity = 1, -->
<!--                               color = "#a87000", -->
<!--                               stroke = FALSE, -->
<!--                               layerId = "Selected2")  -->

<!--       } -->


<!--  }) -->

<!-- ####### Observer generates warning popup if user's geolocation is within a closed area polygon ####### -->

<!-- observe({ -->
<!--   geo <- input$map.m_gps_located -->

<!--   if (is.null(geo)) -->
<!--     return () -->

<!--     content <- paste(sep = "<br/>", -->
<!--   "<b>Warning:</b>", -->
<!--   "You are in a closed area.", -->
<!--   "Trap fishing for spiny lobster is not allowed here.", -->
<!--   "<a href='http://sero.nmfs.noaa.gov/maps_gis_data/fisheries/gom/documents/lobster_trap.txt' target='_blank'>Federal regulations</a>" -->

<!-- ) -->

<!--       proxy <- leafletProxy("map.m",data=closed()) -->
<!--       if(nrow(closed())<1){ -->
<!--         proxy %>% removePopup(layerId = "popup1") -->

<!--       } else { -->
<!--         proxy %>% addPopups(lng=LatLong()$lon,lat=LatLong()$lat, content, -->
<!--                               layerId='popup1') -->

<!--       } -->


<!--  }) -->

<!-- ####### Observer generates warning popup if user's geolocation is within a buffer area polygon ####### -->

<!-- observe({ -->
<!--   geo <- input$map.m_gps_located -->

<!--   if (is.null(geo)) -->
<!--     return () -->

<!--     content <- paste(sep = "<br/>", -->
<!--   "<b>Warning:</b>", -->
<!--   "You are within 1km of a closed area" -->

<!-- ) -->

<!--       proxy <- leafletProxy("map.m",data=buffer()) -->
<!--         if(nrow(buffer())<1){ -->
<!--         proxy %>% removePopup(layerId = "popup2") -->

<!--       } else { -->
<!--         proxy %>% addPopups(lng=LatLong()$lon,lat=LatLong()$lat, content, -->
<!--                               layerId='popup2') -->

<!--       } -->


<!--  }) -->

<!-- ####### Observer generates popup if user's geolocation is NOT within a closed area/buffer polygon ####### -->

<!-- observe({ -->
<!--   geo <- input$map.m_gps_located -->

<!--   if (is.null(geo)) -->
<!--     return () -->

<!--     content <- paste(sep = "<br/>", -->
<!--   "<b>Congrats!</b>", -->
<!--   "You aren't in a closed area." -->

<!-- ) -->

<!--       proxy <- leafletProxy("map.m",data=notclosed()) -->
<!--       if(nrow(notclosed())>=1){ -->
<!--         proxy %>% removePopup(layerId = "popup3") -->

<!--       } else { -->
<!--         proxy %>% addPopups(lng=LatLong()$lon,lat=LatLong()$lat, content, -->
<!--                               layerId='popup3') -->

<!--       } -->


<!--  }) -->


<!-- #### updates map bounds based on user's geolocation and add a marker at user's location ### -->
<!--   # observeEvent(input$do,{ -->
<!--   #   if(!is.null(input$map_gps_located)){ -->
<!--   #     map <- leafletProxy("map") -->
<!--   #     dist <- 0.5 -->
<!--   #     lat <- input$lat -->
<!--   #     lng <- input$long -->
<!--   #     map %>% fitBounds(lng - dist, lat - dist, lng + dist, lat + dist) %>% -->
<!--   #     addMarkers(lng,lat) #%>% -->
<!--   #  -->
<!--   #   } -->
<!--   # }) -->

<!--   #output$table <- renderTable(notclosed()) -->
<!-- ``` -->
